### ISSUE TITLE
Please add .pro to file types

### ISSUE THREAD

**Issue by Magnificus36** [Jakehp/language-prolog#12]
When I installed SWI-Prolog it give me the option to choose .pl or .pro as file extension to be associated. Since I use .pl for perl files (have Padre as default program for .pl) I selected .pro as the extension for prolog files.

**Comment by Jakehp** [comment]
Added [pro support](https://github.com/Jakehp/language-prolog/commit/3636ef25dd46aa7b786f59933fe6fd67beea8833) in [0.10.0](https://github.com/Jakehp/language-prolog/commit/bea4446df28cd0cfaf197ff8ee503d2df732be63)
